version: '3.9'
services:
  db:
    image: mysql:8.0.33
    container_name: bytes4all-db
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3308
    ports:
      - 3308:3308
    expose:
      - 3308
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - bytes4all-network
  bytes4all:
    image: edielsonassis/bytes4all
    container_name: bytes4all-api
    restart: always
    build: ./src
    working_dir: /bytes4all
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:mysql://db:3308/${DATABASE_NAME}?useTimezone=true&serverTimezone=UTC
      SPRING.DATASOURCE.USERNAME: ${DATABASE_USERNAME}
      SPRING.DATASOURCE.PASSWORD: ${DATABASE_PASSWORD}
      ALLOWED_MAPPINGS: ${ALLOWED_MAPPINGS}
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}
      ALLOWED_METHODS: ${ALLOWED_METHODS}
      ALLOWED_HEADERS: ${ALLOWED_HEADERS}
      MAX_AGE: ${MAX_AGE}
    ports:
      - 80:80
    command: mvn spring-boot:run
    depends_on:
      - db
    networks:
      - bytes4all-network
networks:
  bytes4all-network:
    driver: bridge
volumes:
  mysql-data: