# Server settings
server:
  port: 80
  error:
    include-stacktrace: never

# CORS settings
cors:
  allowedMappings: /**
  allowedOrigins: http://localhost:3000
  allowedMethods: GET,POST,PUT,DELETE,PATCH
  allowedHeaders: Content-Type,Authorization,Access-Control-Allow-Origin
  maxAge: 3600

# Security JWT settings
security:
  jwt:
    token:
      secret-key: ${SECRET_KEY:1234567}
      expiration-length: ${EXPIRATION_TOKEN:1}
      refresh-expiration-length: ${EXPIRATION_REFRESH_TOKEN:1}

# Spring datasource settings
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bytes4all?useTimezone=true&serverTimezone=UTC
    username: root
    password: admin123
  
# Spring JPA settings  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

# File settings
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 4MB
      max-request-size: 12MB

file:
  upload-dir: /bytes4all/ebook  

# SpringDoc settings
springdoc:
  pathsToMatch: /api/v1/**
  swagger-ui:
    use-root-path: true