version: '3.9'
services:
  db:
    image: mysql:8.0.33
    container_name: bytes4all-db
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_USER: docker
      MYSQL_PASSWORD: admin123
      MYSQL_DATABASE: bytes4all
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3308
    ports:
      - 3308:3308
    expose:
      - 3308
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - bytes4all-network
  bytes4all:
    image: edielsonassis/bytes4all
    container_name: bytes4all-api
    restart: always
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:mysql://db:3308/bytes4all?useTimezone=true&serverTimezone=UTC
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: admin123
    ports:
      - 80:80
    command: mvn spring-boot:run
    depends_on:
      - db
    networks:
      - bytes4all-network
networks:
  bytes4all-network:
    driver: bridge
volumes:
  mysql-data: